name: CI
on: { push: { branches: [main] } }
jobs:
  build:
    runs-on: ubuntu-latest
    defaults: { run: { shell: bash } }
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Clone Submodules
        run: git submodule update --init --depth=1
      - name: Build Linux
        run: ./build.sh -DLITE_VERSION='"'git-`git rev-parse --short HEAD`'"' && tar -czvf lite-xl-linux.tar.gz lite-xl data
      - name: Build Windows
        run: sudo apt-get install mingw-w64 && ./build.sh clean && CC=i686-w64-mingw32-gcc AR=i686-w64-mingw32-gcc-ar SDL_CONFIGURE="--host=i686-w64-mingw32" ./build.sh -DLITE_VERSION='"'git-`git rev-parse --short HEAD`'"' && zip lite-xl.zip lite-xl.exe data
      - name: Create Release
        env: { GITHUB_TOKEN: ${{ github.token }} }
        run: gh release create -t 'Continuous Release' git-`git rev-parse --short HEAD` *.zip *.tar.gz

