name: CI
on:
  push:
    branches:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Clone Submodules
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Build Linux
        run: ./build.sh && tar -czvf lite-xl.tar.gz lite-xl data
      - name: Upload Linux
        uses: actions/upload-artifact@v3
        with:
          name: lite-xl-linux.tar.gz
          path: lite-xl.tar.gz
      - name: Build Windows
        run: apt-get install mingw-w64 && CC=i686-w64-mingw32-gcc AR=i686-w64-mingw32-gcc-ar SDL_CONFIGURE="--host=i686-w64-mingw32" ./build.sh && zip lite-xl.zip lite-xl.exe data
      - name: Upload Windows
        uses: actions/upload-artifact@v3
        with:
          name: lite-lx-linux.tar.gz
          path: lite-xl.zip

